language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

dist: precise

before_script: composer install

jobs:
  include:
  - stage: test
    script: composer test
  - stage: deploy
    script: skip     # usually you do not want to rerun any tests
    deploy:
      provider: script
      script: curl -XPOST -f -H'content-type:application/json' "https://packagist.org/api/update-package?username=emartech&apiToken=${PACKAGIST_API_TOKEN}" -d"{\"repository\":{\"url\":\"${PACKAGIST_PACKAGE_URL}\"}}"
